### PR TITLE
fix: fixed ignored error, added toast for error messages

### LINKED ISSUE #62: web-wallet improvment - Handle user deleting IDB case
-snap derived viewing key is now only aquired when installing snap, in case user deletes IDB manually from browser no error or option to get viewing key again is possible

### PR DESCRIPTION
**Pull request by irubido**
Closes #62

### CODE REVIEW

File: packages/web-wallet/src/context/WebzjsContext.tsx [hunk 1]
```diff
@@ -146,11 +147,7 @@ export const WebZjsProvider = ({ children }: { children: React.ReactNode }) => {
 
   useEffect(() => {
     if (state.error) {
-      const timeout = setTimeout(() => {
-        dispatch({ type: 'set-error', payload: null });
-      }, 10000);
```
Comment (Lykhoyda) [inline packages/web-wallet/src/context/WebzjsContext.tsx:151]: this logic clears the errors as webz-wallet might have some during the sync state, but it will keep running anyway. So this logic is still required

File: packages/web-wallet/src/context/WebzjsContext.tsx [hunk 2]
```diff
@@ -172,6 +169,7 @@ export const WebZjsProvider = ({ children }: { children: React.ReactNode }) => {
 
   return (
     <WebZjsContext.Provider value={{ state, dispatch }}>
+      <Toaster />
```
[the remark this answers is not in the document]
Comment (irubido) [reply packages/web-wallet/src/context/WebzjsContext.tsx:172]: Toaster component should be in parent rather then every component that needs to display error. 
Alternatively it has its wrapper for displaying errors across the app. For current scope it only displays WebZjsContext-s errors.

File: packages/web-wallet/src/context/WebzjsContext.tsx (hunk 1 above)
Comment (irubido) [reply packages/web-wallet/src/context/WebzjsContext.tsx:151]: It cleared WebZjsContext-s ` state.error` which wasn't even used in the app, it was just set and cleared for no reason.

Now its used by react-hot-toast which removes the toast after set duration.
